use_frameworks!

platform :ios, '9.0'

target 'AnnounceKit_Example' do
  pod 'AnnounceKit', :path => '../'

  target 'AnnounceKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
