use_frameworks!

platform :ios, '11.0'

target 'AnnounceKit_Example' do
  pod 'AnnounceKit'

  target 'AnnounceKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
